SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/AtestadosMedicos/AtestadoMedicoViewModel.cs
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Medicos.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Pacientes.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Configuracoes.Empresas.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Manutencoes.MailingTemplates.Dto;
using System.Collections.Generic;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.AtestadosMedicos
{
    public class AtestadoMedicoViewModel
    {
        public virtual ICollection<MailingTemplateDto> Templates { get; set; }

        public virtual PacienteDto Paciente { get; set; }

        public virtual MedicoDto Medico { get; set; }

        public virtual EmpresaDto Empresa { get; set; }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/FichasPacientes/FichasPacientesViewModel.cs
using SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Pacientes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.FichasPacientes
{
    public class FichasPacientesViewModel
    {
        public string Filtro { get; set; }

        public bool IsEditMode { get { return this.CriarOuEditarPacienteModalViewModel.Id > 0; } }
        public CriarOuEditarPacienteModalViewModel CriarOuEditarPacienteModalViewModel { get; set; }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/Home/AssistenciaisViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.ClassesAplicacao.Services.Atendimentos.Atendimentos.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Prescricoes.PrescricoesStatus.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Medicos.Dto;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.Home
{
    [AutoMap(typeof(AtendimentoDto))]
    public class AssistenciaisViewModel : AtendimentoDto
    {
        public SelectList Empresas { get; set; }

        public SelectList UnidadesOrganizacionais { get; set; }

        public string Filtro { get; set; }

        public virtual ICollection<AtendimentoDto> Atendimentos { get; set; }

        public bool IsEditMode { get { return Id > 0; } }

       

        public AssistenciaisViewModel(AtendimentoDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/Internacoes/Home/AssistenciaisViewModel.cs
using SW10.SWMANAGER.ClassesAplicacao.Services.Atendimentos.Atendimentos.Dto;
using System.Collections.Generic;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.Internacoes.Home
{
    public class AssistenciaisViewModel
    {
        public string Filtro { get; set; }

        public ICollection<AtendimentoDto> Atendimentos { get; set; }

    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/Prescricoes/CriarOuEditarPrescricaoViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.ClassesAplicacao.Services.Assistenciais.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Prescricoes.Divisoes.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Prescricoes.TiposRespostas.Dto;
using System.Collections.Generic;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.Prescricoes
{
    [AutoMap(typeof(PrescricaoMedicaDto))]
    public class CriarOuEditarPrescricaoViewModel : PrescricaoMedicaDto
    {
        public bool IsEditMode { get { return Id > 0; } }

        public ICollection<DivisaoDto> Divisoes { get; set; }

        public ICollection<TipoRespostaDto> TiposRespostas { get; set; }

        public CriarOuEditarPrescricaoViewModel(PrescricaoMedicaDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/Prescricoes/PrescricaoItemRespostaViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.ClassesAplicacao.Services.Assistenciais.Dto;
using System.Collections.Generic;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.Prescricoes
{
    [AutoMap(typeof(PrescricaoItemRespostaDto))]
    public class PrescricaoItemRespostaViewModel : PrescricaoItemRespostaDto
    {

        public bool IsEditMode { get { return Id > 0; } }

        public PrescricaoItemRespostaViewModel(PrescricaoItemRespostaDto output)
        {
            output.MapTo(this);
        }

    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/Relatorios/FiltroModel.cs
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Prescricoes.TiposRespostas.Dto;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.Relatorios
{
    public class FiltroModel
    {
        public string Titulo { get; set; }
        public string NomeHospital { get; set; }
        public string NomeUsuario { get; set; }
        public string DataHora { get; set; }
        public IList<SelectListItem> Empresas { get; set; }
        public List<RespostaDto> Respostas { get; set; }
        public string Value { get; set; }
        public string Text { get; set; }
        public string Paciente { get; set; }
        public string Nascimento { get; set; }
        public long? PrescricaoId { get; set; }
        public string Prescricao { get; set; }
        public string PrescricaoItem { get; set; }
        public string Atendimento { get; set; }
        public string Convenio { get; set; }
        public string Internacao { get; set; }
        public string UnidadeOrganizacional { get; set; }
        public string Leito { get; set; }
        public long Empresa { get; set; }
        public string Medico { get; set; }
        public string CRM { get; set; }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/Relatorios/TesteObjeto.cs
namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.Relatorios
{
    public class TesteObjeto
    {
        public string CodAtendimento { get; set; }
        public string DataInternacao { get; set; }
        public string CodPaciente { get; set; }
        public string Paciente { get; set; }
        public string Origem { get; set; }
        public string Empresa { get; set; }
        public string Convenio { get; set; }
        public string UnidOrganizacional { get; set; }
        public string Leito { get; set; }
        public string Medico { get; set; }
        public string Idade { get; set; }
        public string DiasInternado { get; set; }
        public object Value { get; internal set; }
        public object Text { get; internal set; }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/SolicitacoesExames/CriarOuEditarSolicitacaoExameItemViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.Authorization.Users.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Assistenciais.Dto;
using System.Web.Mvc;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.SolicitacoesExames
{
    [AutoMap(typeof(SolicitacaoExameItemDto))]
    public class CriarOuEditarSolicitacaoExameItemViewModel : SolicitacaoExameItemDto
    {
        public UserEditDto UpdateUser { get; set; }

        public bool IsEditMode { get { return Id > 0; } }

        public CriarOuEditarSolicitacaoExameItemViewModel(SolicitacaoExameItemDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Assistenciais/SolicitacoesExames/CriarOuEditarSolicitacaoExameViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.Authorization.Users.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Assistenciais.Dto;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Assistenciais.SolicitacoesExames
{
    [AutoMap(typeof(SolicitacaoExameDto))]
    public class CriarOuEditarSolicitacaoExameViewModel : SolicitacaoExameDto
    {
        public UserEditDto UpdateUser { get; set; }

        public bool IsEditMode { get { return Id > 0; } }

        public CriarOuEditarSolicitacaoExameViewModel(SolicitacaoExameDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/Atestados/AtestadoViewModel.cs
namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.Atestados
{
    public class AtestadoViewModel
    {
        public string Filtro { get; set; }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/Atestados/CriarOuEditarAtestadoViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Atestados.Dto;
using System.Web.Mvc;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.Atestados
{
    [AutoMap(typeof(AtestadoDto))]
    public class CriarOuEditarAtestadoViewModel : AtestadoDto
    {
        public bool IsEditMode { get { return Id > 0; } }

        public SelectList TiposAtestados { get; set; }

        public SelectList ModelosAtestados { get; set; }

        public CriarOuEditarAtestadoViewModel(AtestadoDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/ModelosAtestados/CriarOuEditarModeloAtestadoViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Atestados.Dto;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.ModelosAtestados
{
    [AutoMap(typeof(ModeloAtestadoDto))]
    public class CriarOuEditarModeloAtestadoViewModel : ModeloAtestadoDto
    {
        public bool IsEditMode { get { return Id > 0; } }

        public CriarOuEditarModeloAtestadoViewModel(ModeloAtestadoDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/ModelosAtestados/ModeloAtestadoViewModel.cs
namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.ModelosAtestados
{
    public class ModeloAtestadoViewModel
    {
        public string Filtro { get; set; }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/Prescricoes/Divisoes/CriarOuEditarDivisaoViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Prescricoes.Divisoes.Dto;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Prescricoes.TiposRespostas.Dto;
using System.Collections.Generic;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.Prescricoes.Divisoes
{
    [AutoMap(typeof(DivisaoDto))]
    public class CriarOuEditarDivisaoViewModel : DivisaoDto
    {
        public bool IsEditMode { get { return Id > 0; } }

        //public ICollection<TipoRespostaDto> TiposRespostasDisponiveis { get; set; }

        public CriarOuEditarDivisaoViewModel(DivisaoDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/Prescricoes/Divisoes/CriarOuEditarTipoPrescricaoViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Prescricoes.TiposPrescricoes.Dto;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.Prescricoes.Divisoes
{
    [AutoMap(typeof(TipoPrescricaoDto))]
    public class CriarOuEditarTipoPrescricaoViewModel : TipoPrescricaoDto
    {
        public bool IsEditMode { get { return Id > 0; } }

        public CriarOuEditarTipoPrescricaoViewModel(TipoPrescricaoDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/Prescricoes/Divisoes/DivisaoViewModel.cs
namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.Prescricoes.Divisoes
{
    public class DivisaoViewModel
    {
        public string Filtro { get; set; }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/Prescricoes/FormasAplicacoes/CriarOuEditarFormaAplicacaoViewModel.cs
using Abp.AutoMapper;
using SW10.SWMANAGER.ClassesAplicacao.Services.Cadastros.Assistenciais.Prescricoes.FormasAplicacao.Dto;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.Prescricoes.FormasAplicacoes
{
    [AutoMap(typeof(FormaAplicacaoDto))]
    public class CriarOuEditarFormaAplicacaoViewModel : FormaAplicacaoDto
    {
        public bool IsEditMode { get { return Id > 0; } }

        public CriarOuEditarFormaAplicacaoViewModel(FormaAplicacaoDto output)
        {
            output.MapTo(this);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/Prescricoes/FormasAplicacoes/FormaAplicacaoViewModel.cs
namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.Prescricoes.FormasAplicacoes
{
    public class FormaAplicacaoViewModel
    {
        public string Filtro { get; set; }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Models/Aplicacao/Cadastros/Assistenciais/Prescricoes/FormulasEstoques/CriarOuEditarFormulaEstoqueItemViewModel.cs
using Abp.AutoMapper;

namespace SW10.SWMANAGER.Web.Areas.Mpa.Models.Aplicacao.Cadastros.Assistenciais.Prescricoes.FormulasEstoques
{
    //[AutoMap(typeof(FormulaEstoqueItemDto))]
    //public class CriarOuEditarFormulaEstoqueItemViewModel : FormulaEstoqueItemDto
    //{
    //    public bool IsEditMode { get { return Id > 0; } }

    //    public CriarOuEditarFormulaEstoqueItemViewModel(FormulaEstoqueItemDto output)
    //    {
    //        output.MapTo(this);
    //    }
    //}
}

SW10.SWMANAGER.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using SW10.SWMANAGER.Configuration;
using SW10.SWMANAGER.Sessions;
using SW10.SWMANAGER.Web.Models.Layout;
using SW10.SWMANAGER.Web.Navigation;

namespace SW10.SWMANAGER.Web.Controllers
{
    /// <summary>
    /// Layout for 'front end' pages.
    /// </summary>
    public class LayoutController : SWMANAGERControllerBase
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            ISessionAppService sessionAppService, 
            IUserNavigationManager userNavigationManager, 
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _sessionAppService = sessionAppService;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult Header(string currentPageName = "")
        {
            var headerModel = new HeaderViewModel();
            
            if (AbpSession.UserId.HasValue)
            {
                headerModel.LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations());
            }

            headerModel.Languages = _languageManager.GetLanguages();
            headerModel.CurrentLanguage = _languageManager.CurrentLanguage;
            
            headerModel.Menu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync(FrontEndNavigationProvider.MenuName, AbpSession.ToUserIdentifier()));
            headerModel.CurrentPageName = currentPageName;

            headerModel.IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled;
            headerModel.TenantRegistrationEnabled = SettingManager.GetSettingValue<bool>(AppSettings.TenantManagement.AllowSelfRegistration);

            return PartialView("~/Views/Layout/_Header.cshtml", headerModel);
        }
    }
}

SW10.SWMANAGER.Web/Areas/Mpa/Views/Aplicacao/Assistenciais/Home/_BotoesAcao.cshtml
@model SW10.SWMANAGER.ClassesAplicacao.Services.Atendimentos.Atendimentos.Dto.AtendimentoDto


<div class="row">
    <div class="col-sm-12 alert alert-info">
        <span>@L("Acoes")</span>
    </div>
</div>
<div class="row">
    <div class="col-sm-2">
        <button name="Editar" id="btn-editar-atendimento-@(Model.Id)" class="btn btn-warning"><i class="icon-edit-sign"></i>@L("Editar")</button>
    </div>
    <div class="col-sm-2">
        <button name="Imprimir" id="btn-editar" class="btn btn-primary"><i class="icon-print"></i>@L("Imprimir")</button>
    </div>
    <div class="col-sm-2">
        <button name="Exportar" id="btn-editar" class="btn btn-default"><i class="icon-edit-sign"></i>@L("Exportar")</button>
    </div>
    <div class="col-sm-2">
        <button name="Exportar" id="btn-editar" class="btn btn-success"><i class="icon-edit-sign"></i>@L("Exportar")</button>
    </div>
    <div class="col-sm-2">
        <button name="Exportar" id="btn-editar" class="btn btn-danger"><i class="icon-edit-sign"></i>@L("Exportar")</button>
    </div>
    <div class="col-sm-2">
        <button name="Exportar" id="btn-editar" class="btn btn-info"><i class="icon-edit-sign"></i>@L("Exportar")</button>
    </div>
</div>

<div class="row">
    <div class="col-sm-2">
        <button name="Editar" id="btn-editar" class="btn btn-warning"><i class="icon-edit-sign"></i>@L("Editar")</button>
    </div>
    <div class="col-sm-2">
        <button name="Imprimir" id="btn-editar" class="btn btn-primary"><i class="icon-print"></i>@L("Imprimir")</button>
    </div>
    <div class="col-sm-2">
        <button name="Exportar" id="btn-editar" class="btn btn-default"><i class="icon-edit-sign"></i>@L("Exportar")</button>
    </div>
    <div class="col-sm-2">
        <button name="Exportar" id="btn-editar" class="btn btn-success"><i class="icon-edit-sign"></i>@L("Exportar")</button>
    </div>
    <div class="col-sm-2">
        <button name="Exportar" id="btn-editar" class="btn btn-danger"><i class="icon-edit-sign"></i>@L("Exportar")</button>
    </div>
    <div class="col-sm-2">
        <button name="Exportar" id="btn-editar" class="btn btn-info"><i class="icon-edit-sign"></i>@L("Exportar")</button>
    </div>
</div>

SW10.SWMANAGER.Web/Areas/Mpa/Views/Aplicacao/Assistenciais/Home/_LerAtendimento.cshtml
@using SW10.SWMANAGER.Web.Areas.Mpa.Startup;

@{
    var atendimento = TempData.Peek("Atendimento") as SW10.SWMANAGER.ClassesAplicacao.Services.Atendimentos.Atendimentos.Dto.AtendimentoDto;
}

@model SW10.SWMANAGER.ClassesAplicacao.Services.Atendimentos.Atendimentos.Dto.AtendimentoDto

<script>
    localStorage["DataAtendimento"] = '@(string.Format("{0:D4}{1:D2}{2:D2}T{3:D2}{4:D2}{5:D2}",atendimento.DataRegistro.Year,atendimento.DataRegistro.Month,atendimento.DataRegistro.Day,atendimento.DataRegistro.Hour,atendimento.DataRegistro.Minute,atendimento.DataRegistro.Second))';
    localStorage["AtendimentoId"] = '@(atendimento.Id)';
    var _senhaService = abp.services.app.senha;
    var _terminalSenhasService = abp.services.app.terminalSenhas;
    $(document).ready(function () {
        $.fn.modal.Constructor.prototype.enforceFocus = function () { };
        if ($('#movimentacao-senha-id').val() !== null && $('#movimentacao-senha-id').val() !== undefined) {
            $('#chamar-senha').show();
            $('#combo-local-chamada').hide();
        }
        else {
            $('#chamar-senha').hide();
            $('#combo-local-chamada').show();
        }
    });
    $('#chamar-senha').on('click', function (e) {
        e.preventDefault();
       _terminalSenhasService.chamarSenha(
            $('#tipo-local-chamada-id').val(),
            $('#local-chamada-id').val(),
            $('#movimentacao-senha-id').val()
        );
        $.cookie('localChamada', $('#local-chamada-id').val());
        $('#chamar-senha').hide();
        $('#combo-local-chamada').show();
    });
    selectSW('.selectTipoLocalChamada2', "/api/services/app/TipoLocalChamada/ListarTipoLocalChamadaDropdown");

    $('#tipo-local-chamada-id-2').on('change', function () {
        _senhaService.criarMovimento('@(atendimento.Id)', $('#tipo-local-chamada-id-2').val())
        .done(function () {
            abp.notify.info(app.localize('SenhaEncaminhada'));
            $('#combo-local-chamada').hide();
        })
    });

    var _novoTevMovimento = new app.ModalManager({
        viewUrl: abp.appPath + 'Mpa/Assistenciais/_TevMovimento',
        scriptUrl: abp.appPath + 'Areas/Mpa/Views/Aplicacao/Assistenciais/Medicos/Prescricoes/_TevMovimento.js',
        modalClass: 'NovoTevMovimentoModal'
    });


    var _registrosArquivos = new app.ModalManager({
        viewUrl: abp.appPath + 'Mpa/Assistenciais/ListarRegistroArquivos',
        scriptUrl: abp.appPath + 'Areas/Mpa/Views/Aplicacao/Assistenciais/RegistrosArquivos/Index.js',
        modalClass: 'ListarRegistroArquivos'
    });



    $('#ChamadaPep').on('click', function (e) {
       // e.preventDefault();

        _registrosArquivos.open({ id: '@(atendimento.Id)' });
        

    });




    //$('#novo-tev-movimento-@(atendimento.Id)').on('click', function (e) {
    function novoTevMovimento() {
        //e.preventDefault();
        _novoTevMovimento.open({
            atendimentoId: '@(atendimento.Id)'
        });
    }
    //});

</script>

<div class="row">
    <div class="col-sm-12" id="header-area-@atendimento.Id" data-id="@Model.Id">
        @*@Html.Action("HeaderAtendimento", "Assistenciais", new { id = Model.Id })*@
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-plus-sign-alt"></i>
                    @(string.Format("{0}: {1} - {2:D10}{3}", L("Prontuario"), atendimento.Paciente.NomeCompleto, L("Atendimento") + ": " + atendimento.Codigo, atendimento.Paciente.Nascimento.HasValue ? " - " + L("Nascimento") + ": " + atendimento.Paciente.Nascimento.Value.ToString("dd/MM/yyyy") : string.Empty))
                </div>
                <!--ações page-->


                <div class="actions">
                    <button class="btn btn-circle btn-icon-only btn-default fa fa-tasks fa-3x" id="chamar-senha" title="@L("ChamarSenha")"></button>
                </div>
            </div>
            <div class="portlet-body">
                <div id="conteudo-modulo-@atendimento.Id" class="hidden">
                    <div class="row">
                        <div class="col-md-12">
                            <iframe name="FormularioDinamicoArea" frameborder="0" id="formulario-dinamico-area-@atendimento.Id" src="" class="embed-responsive-item" />
                        </div>
                    </div>
                </div>
                <div id="menu-modulo-@atendimento.Id" data-current-page-name="@ViewBag.CurrentPageName" data-menu-name="@MpaNavigationProvider.AssistencialMenuName" data-key="@Model.Id">
                    @Html.Action("SidebarTab", "Layout", new { currentPageName = ViewBag.CurrentPageName, menuName = MpaNavigationProvider.AssistencialMenuName, key = Model.Id })
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-md-3 left" id="tev-movimento">
                        @Html.Partial("~/Areas/Mpa/Views/Aplicacao/Assistenciais/Home/_ControlaTev.cshtml")
                    </div>
                    <div class="col-md-6">&nbsp;</div>
                    <div class="col-md-3" id="combo-local-chamada">
                        @if (atendimento.IsAmbulatorioEmergencia)
                        {
                            <div class="form-inline float-right">
                                <label>@L("EncaminharPaciente")</label>
                                <select name="TipoLocalChamadaId" id="tipo-local-chamada-id-2" class="form-control select2 selectTipoLocalChamada2"></select>
                            </div>
                        }

                        <div class="actions">
                            <button class="btn btn-circle btn-icon-only btn-default fa fa-tasks fa-3x" id="ChamadaPep" title="PEP - Prontuário Eletrônico do Paciente"></button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>